### ISSUE TITLE
pyta not compatible with python 3.6.3

### ISSUE THREAD

**Issue by lujiajing1126** [pyta-uoft/pyta#317]
I use the latest version of `pyta` installed with `pip3`, but it stop working.

```
Traceback (most recent call last):
  File "checker.py", line 5, in <module>
    import python_ta
  File "/usr/local/lib/python3.6/site-packages/python_ta/__init__.py", line 37, in <module>
    from .patches import patch_all
  File "/usr/local/lib/python3.6/site-packages/python_ta/patches/__init__.py", line 4, in <module>
    from .type import patch_type_inference_transform
  File "/usr/local/lib/python3.6/site-packages/python_ta/patches/type.py", line 4, in <module>
    from ..transforms.type_inference_visitor import TypeInferer
  File "/usr/local/lib/python3.6/site-packages/python_ta/transforms/type_inference_visitor.py", line 5, in <module>
    from typing import CallableMeta, TupleMeta, Union, _gorg, _geqv, _ForwardRef
ImportError: cannot import name '_gorg'
```

**Comment by david-yz-liu** [comment]
Thanks! Fixed in #316.
