### ISSUE TITLE
SyntaxErro while importing python_ta

### ISSUE THREAD

**Issue by AlvinChe** [pyta-uoft/pyta#526]
````
Python 3.6.5 (default, Apr 25 2018, 14:23:58) 
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import python_ta
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/astroid/builder.py", line 158, in _data_build
    node = _parse(data + '\n')
  File "/usr/local/lib/python3.6/site-packages/astroid/_ast.py", line 31, in _parse
    return _get_parser_module(parse_python_two=parse_python_two).parse(string)
  File "/usr/local/lib/python3.6/site-packages/typed_ast/ast3.py", line 58, in parse
    return _ast3._parse(source, filename, mode, feature_version)
  File "<unknown>", line 1079
    start: Optional[int] = ...  # type: Optional[int]
                                                    ^
SyntaxError: misplaced type annotation

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/python_ta/__init__.py", line 37, in <module>
    from .patches import patch_all
  File "/usr/local/lib/python3.6/site-packages/python_ta/patches/__init__.py", line 4, in <module>
    from .type import patch_type_inference_transform
  File "/usr/local/lib/python3.6/site-packages/python_ta/patches/type.py", line 4, in <module>
    from ..transforms.type_inference_visitor import TypeInferer
  File "/usr/local/lib/python3.6/site-packages/python_ta/transforms/type_inference_visitor.py", line 35, in <module>
    class TypeInferer:
  File "/usr/local/lib/python3.6/site-packages/python_ta/transforms/type_inference_visitor.py", line 39, in TypeInferer
    type_store = TypeStore(type_constraints)
  File "/usr/local/lib/python3.6/site-packages/python_ta/typecheck/type_store.py", line 15, in __init__
    module = astroid.parse(contents)
  File "/usr/local/lib/python3.6/site-packages/astroid/builder.py", line 257, in parse
    return builder.string_build(code, modname=module_name, path=path)
  File "/usr/local/lib/python3.6/site-packages/astroid/builder.py", line 132, in string_build
    module = self._data_build(data, modname, path)
  File "/usr/local/lib/python3.6/site-packages/astroid/builder.py", line 162, in _data_build
    source=data, modname=modname, path=path, error=exc) from exc
astroid.exceptions.AstroidSyntaxError: Parsing Python code failed:
misplaced type annotation (<unknown>, line 1079)
>>> 
[python_ta.zip](https://github.com/pyta-uoft/pyta/files/2259152/python_ta.zip)
```

i met this problem i don't what to do , hope can get help , thank you.

**Comment by david-yz-liu** [comment]
Hey, sorry I missed this issue until now. This has been fixed in the latest version of PythonTA (1.4.0), but requires Python3.7 to use. Unfortunately this is the best we can do to support you at this time. If you're able to update your Python version and PythonTA versions, everything should work just fine.
